volumes:
  mariadb_data:
  static_volume:
  proxy_certs:
  proxy_vhost:
  proxy_html:

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.4
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy_certs:/etc/nginx/certs:ro
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion:2.2
    container_name: acme-companion
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      DEFAULT_EMAIL: contact@sherwheels.fr
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy_certs:/etc/nginx/certs
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html

  db:
    image: mariadb:10.5
    container_name: BD
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    container_name: Sherwheels
    restart: always
    depends_on:
      - db
    expose:
      - "8000"
    environment:
      VIRTUAL_HOST: sherwheels.fr,www.sherwheels.fr
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: sherwheels.fr,www.sherwheels.fr
      LETSENCRYPT_EMAIL: contact@sherwheels.fr
    env_file: .env
    command: >
      sh -euc "
        until mysqladmin ping -h db --silent; do sleep 2; done
        python manage.py migrate --no-input
        mkdir -p /app/staticfiles
        python manage.py collectstatic --no-input --clear
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: Phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
