# Generated by Django 5.1.4 on 2025-01-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicompte', '0002_photouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
