# Generated by Django 5.1.4 on 2025-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
