# .github/workflows/deploy.yml
name: 📦 Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Ajouter la clé SSH à l’agent
        # Change ici pour un tag qui existe vraiment
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Déployer via SSH
        run: |
          ssh -o StrictHostKeyChecking=no \
            -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            'cd /srv/ShareWheels && ./deploy.sh'
